class TestData:
    NAME = "Faroque"
    COUNTRY = "Bangladesh"
    ERR_MSG = "Please enter your name"
    PRODUCT_ONE = "Jordan 6 Rings"
    PRODUCT_ONE_PRICE = "165.0"
    PRODUCT_TWO = "PG 3"
    PRODUCT_TWO_PRICE = ""
    TOC_TITLE = "Terms Of Conditions"
    GENDER = "Female"